-- CreateEnum
CREATE TYPE "OnboardingFileStatus" AS ENUM ('DRAFT', 'SUBMITTED');

-- CreateTable
CREATE TABLE "onboarding_files" (
    "id" UUID NOT NULL,
    "token" TEXT NOT NULL,
    "owner_id" UUID NOT NULL,
    "status" "OnboardingFileStatus" NOT NULL DEFAULT 'DRAFT',
    "num_owners" TEXT,
    "title_property" TEXT,
    "property_type_description" TEXT,
    "num_levels" INTEGER,
    "total_beds" INTEGER,
    "owner_first_name" TEXT,
    "owner_last_name" TEXT,
    "owner_fiscal_code" TEXT,
    "billing_type" TEXT,
    "owner_language" TEXT,
    "owner_birth_date" TEXT,
    "owner_phone" TEXT,
    "owner_phone_alt" TEXT,
    "owner_email" TEXT,
    "owner_email_alt" TEXT,
    "residence_address" TEXT,
    "residence_zip" TEXT,
    "residence_country" TEXT,
    "document_type" TEXT,
    "document_number" TEXT,
    "document_issue_place" TEXT,
    "document_issue_date" TEXT,
    "document_file_url" TEXT,
    "bank_account_holder" TEXT,
    "bank_iban" TEXT,
    "bank_name" TEXT,
    "bank_bic_swift" TEXT,
    "property_condition" TEXT,
    "property_address" TEXT,
    "property_zip" TEXT,
    "property_floor" TEXT,
    "property_intercom_name" TEXT,
    "property_door_number" TEXT,
    "property_sqm_internal" INTEGER,
    "property_sqm_external" INTEGER,
    "num_rooms" INTEGER,
    "rooms" JSONB,
    "has_sofa_bed" BOOLEAN,
    "num_bathrooms" INTEGER,
    "bathrooms" JSONB,
    "num_kitchens" INTEGER,
    "kitchen_layout" TEXT,
    "kitchen_type" TEXT,
    "kitchen_amenities" JSONB,
    "kitchen_extra" TEXT,
    "kitchen_notes" TEXT,
    "general_amenities" JSONB,
    "internet_provider" TEXT,
    "wifi_name" TEXT,
    "wifi_password" TEXT,
    "modem_sim_number" TEXT,
    "modem_serial_number" TEXT,
    "has_self_checkin_device" BOOLEAN,
    "self_checkin_code" TEXT,
    "self_checkin_position" TEXT,
    "self_checkin_photo_url" TEXT,
    "has_parking" BOOLEAN,
    "parking_photo_url" TEXT,
    "has_disabled_access" BOOLEAN,
    "services" JSONB,
    "allows_pets" BOOLEAN,
    "other_services" TEXT,
    "allows_smoking" BOOLEAN,
    "safety_equipment" JSONB,
    "gas_tank_position" TEXT,
    "gas_connection_type" TEXT,
    "gas_photo_url" TEXT,
    "electricity_internal_photo_url" TEXT,
    "electricity_internal_position" TEXT,
    "electricity_external_photo_url" TEXT,
    "electricity_external_position" TEXT,
    "water_internal_position" TEXT,
    "water_internal_photo_url" TEXT,
    "water_external_position" TEXT,
    "water_external_photo_url" TEXT,
    "planimetry_file_url" TEXT,
    "cadastral_survey_file_url" TEXT,
    "cin_file_url" TEXT,
    "alloggiati_web_file_url" TEXT,
    "ross1000_credentials" TEXT,
    "has_waste_bins" BOOLEAN,
    "waste_calendar_photo_url" TEXT,
    "waste_bins_location_photo_url" TEXT,
    "waste_notes" TEXT,
    "keys_availability_date" TEXT,
    "dates_to_block" TEXT,
    "privacy_consent" BOOLEAN,
    "submitted_at" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "onboarding_files_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "onboarding_files_token_key" ON "onboarding_files"("token");

-- CreateIndex
CREATE UNIQUE INDEX "onboarding_files_owner_id_key" ON "onboarding_files"("owner_id");

-- AddForeignKey
ALTER TABLE "onboarding_files" ADD CONSTRAINT "onboarding_files_owner_id_fkey" FOREIGN KEY ("owner_id") REFERENCES "owners"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
